//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laptop
    {
        public int LaptopID { get; set; }
        public string OS { get; set; }
        public string ScreenWidth { get; set; }
        public string CPU { get; set; }
        public string RAM { get; set; }
        public string HardDisk { get; set; }
        public string Port { get; set; }
        public string Battery { get; set; }
        public string ScreenResolution { get; set; }
        public string GPU { get; set; }
        public string Wifi { get; set; }
        public string Size { get; set; }
        public string Weight { get; set; }
        public string Special { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
