//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public int PhoneID { get; set; }
        public string OS { get; set; }
        public string ScreenWidth { get; set; }
        public string CPU { get; set; }
        public string RAM { get; set; }
        public string ROM { get; set; }
        public string Camera { get; set; }
        public string FrontCamera { get; set; }
        public string Battery { get; set; }
        public string ScreenResolution { get; set; }
        public string NFC { get; set; }
        public string HeadphoneJack { get; set; }
        public string Wifi { get; set; }
        public string Sim { get; set; }
        public string Special { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
